### ISSUE TITLE
暂停时操作菜单仍与播放时逻辑一致

### ISSUE THREAD

**Issue by Brianwind** [diana7127/mpv.net-DW#11]
希望增加一个功能选项，设置操作菜单在暂停时也能自动隐藏（如下图圈出部分）

有时候看视频希望暂停来看一些画面细节，这个时候操作菜单常态显示出来就不方便，希望能增加控制选项

![image](https://github.com/diana7127/mpv.net-DW/assets/49585907/c4d4d4e5-d6c7-4bcd-a77b-2a2d79a87716)

**Comment by diana7127** [comment]
在`portable_config`>`scripts`文件夹中，打开`modernx.lua`文件，第50行`showonpause = true,         -- whether to disable the hide timeout on pause`中的`true`改为`false`就可以了

**Comment by Brianwind** [comment]
可以了，非常感谢！
