### ISSUE TITLE
are you going to make mpv.net cm alive?

### ISSUE THREAD

**Issue by sun-shine-boy** [diana7127/mpv.net-DW#2]
are you?

**Comment by diana7127** [comment]
You can update libmpv by yourself. The author of mpv.net and mpv.net_CM are no longer maintaining it, I can't fix the bug from mpv.net and mpv.net_CM. 
What I can do is only updating libmpv, osc, thumbfast and some shaders and filters half-yearly or yearly.

**Comment by zhouxinghong** [comment]
Hello! Please how to update libmpv, osc, thumbfast and some shaders and filters, I would like to contribute to maintain it when I have time. . .

**Comment by diana7127** [comment]
I believe I will update mpv.net-DW based on the frequency of mpv_lazy updates. But also you can find which components need to be updated in the README 'Update' section.

Actually, when you first install it, it will display no border by default. If not, just right click to display the menu, find 'mpv设置 > 功能 > border', and choose 'no'.

**Comment by zhouxinghong** [comment]
Thank you so much! 😜👍But I found a problem. The menu items of this version are different from the mpv.net-6.0.3.2-beta version. Is it possible to synchronize the menu items?

**Comment by diana7127** [comment]
You mean the right-click menu? Or the 'mpv.conf编辑器' menu? If right-click menu, I changed it from mpv.net_CM, which is already different from mpv.net. But you can replace it with the mpv.net version yourself. I won't synchronise the menu from mpv.net or mpv.net_CM, you can assume that the current menu is the mpv.net-DW version, if it makes sense.

**Comment by diana7127** [comment]
I see, you may be referring to the menu "mpv.conf编辑器". This menu from mpv.net_CM has not been updated, so I can't simply synchronize it. You have to ask the author of mpv.net_CM to update to a newer version, if possible.

**Comment by sun-shine-boy** [comment]
Are you updating the mpv.net cm ? i installed mpv.net dm. keep up the good work queen diana.

**Comment by sun-shine-boy** [comment]
> But also you can find which components need to be updated in the README 'Update' section.

what does that mean? should i install smth after installing mpv.net dw ?

**Comment by diana7127** [comment]
> > But also you can find which components need to be updated in the README 'Update' section.
> 
> what does that mean? should i install smth after installing mpv.net dw ?

No need. This is just saying what you need to update if I don't update it for a long time, or if you want to update it by yourself

**Comment by diana7127** [comment]
> Are you updating the mpv.net cm ? i installed mpv.net dw. keep up the good work queen diana. P.s: the new ui is decent. Modern x ispolished and clean pls add more features like this when you could ty,ty,ty,ty.

I'm not the developer of mpv.net_CM. I'm just dealing with some minor updates to DW.
P.S You're the first person to find out I'm a girl.🥰
