### ISSUE TITLE
请问怎么默认打开加载字幕？每次打开视频都得手动载入字幕

### ISSUE THREAD

**Issue by a8778700** [diana7127/mpv.net-DW#3]

**Comment by diana7127** [comment]
新版本中已默认模糊显示音频与字幕，请更新版本或右键查看“mpv设置”中的“字幕”，在“sub-auto”中是否选择了“fuzzy”；如果已经选择了fuzzy，请查看字幕的文件名，如果仅在末尾标记了chs/sc等，其他部分与视频文件名一致，默认是可以识别的。
