### ISSUE TITLE
讨论srt字幕默认字体

### ISSUE THREAD

**Issue by huanghuanhuahuh** [diana7127/mpv.net-DW#4]
个人认为得意黑使用在字幕上可能会影响易读性
或许使用微软雅黑之类的更加合适?

**Comment by diana7127** [comment]
选择得意黑为srt默认字体，是因为它在黑体的基础上字身比较窄，可以在一行中显示更多的字。

不安装得意黑字体的话就会显示系统默认的字体，也算是提供两个选择；如果想用其它字体，可以右键在mpv设置>字幕>sub-font中填写相应的字体名称。
