### ISSUE TITLE
怎样实现双字幕显示？

### ISSUE THREAD

**Issue by Rakau** [diana7127/mpv.net-DW#5]
RT，想加载弹幕

**Comment by diana7127** [comment]
v1.4.0版本新增了次字幕的显示/切换功能，不过由于mpv对双字幕的支持不好，次字幕会自动消除格式，以默认的字幕字体在顶端居中显示，所以更常用于双语字幕显示；至于弹幕的显示，目前我还没有找到可行的方案，欢迎大家讨论研究。

**Comment by Rakau** [comment]
看到了相应的帖子https://404.website/thread-6503-1-1.html，不知道有不有用

**Comment by diana7127** [comment]
我刚刚也看到了这个帖子，里面说的次字幕设置就是v1.4.0版本新增的功能；对于弹幕，帖主建议切换成KikoPlay或者手动合并弹幕和字幕（个人感觉太麻烦了）

**Comment by hooke007** [comment]
> 能从KikoPlay上弄脚本来支持嘛

这是kiko的核心功能，可不是只靠脚本实现的“玩具”功能。但是是双刃剑 —— 把渲染后端锁死在了opengl。

这个问题，要么等上游实现（官方基本不可能，他们不感兴趣）

要么用滤镜，以较高的性能为代价实现。
要么换第三方内核。
后面两种方式记录在这里 https://github.com/hooke007/MPV_lazy/discussions/61

**Comment by diana7127** [comment]
感谢！已经替换了内核，发布了新版本

**Comment by Rakau** [comment]
> 感谢！已经替换了内核，发布了新版本

赞赞！有木有办法让加载的弹幕根据显示器的刷新率来显示？默认的24帧看起来卡卡的

**Comment by hooke007** [comment]
`vf=fps=fps=60`

**Comment by Rakau** [comment]
> `vf=fps=fps=60`

### 看来还是得手动写固定
