### ISSUE TITLE
使用方向键回退后会短暂声音消失

### ISSUE THREAD

**Issue by huanghuanhuahuh** [diana7127/mpv.net-DW#6]
使用方向键回退播放进度后, 有大约半秒到二秒左右会没有声音, 但视频并无卡顿
猜测是缓存的问题? 或许和mpv本身有关? 
如果有描述不清抱歉, 请告诉我需要提供哪些信息
视频是mkv格式, 音频好像是单独封装mka文件
![屏幕截图 2023-04-06 054615](https://user-images.githubusercontent.com/83399440/230219222-252124ba-5749-4d5f-a79c-ea6e6fa6b500.png)

**Comment by hooke007** [comment]
https://github.com/hooke007/MPV_lazy/issues/224#issuecomment-1319188125
