### ISSUE TITLE
关于菜单中“视频滤镜-rife补帧60”功能的BUG

### ISSUE THREAD

**Issue by Rakau** [diana7127/mpv.net-DW#8]
RT，TAB显示的也还是2倍帧数的效果，是否为RIFE自己的BUG？还是我设备的问题？

**Comment by diana7127** [comment]
刚刚试了一下，我这里的rife的倍帧和补帧60都有问题
![Snipaste_2023-04-07_00-59-24](https://user-images.githubusercontent.com/125502871/230427100-49799bec-57e5-4522-88d5-97da656fd6e9.jpg)
![Snipaste_2023-04-07_01-03-01](https://user-images.githubusercontent.com/125502871/230427758-f58eae4e-56dd-4077-8749-2ea1d299fc54.jpg)

**Comment by hooke007** [comment]
他写错了。

thread报错只能是1说明是显卡驱动的问题。

**Comment by diana7127** [comment]
> thread报错只能是1说明是显卡驱动的问题。

好的，谢谢！

**Comment by hooke007** [comment]
因为“他写错了。”

**Comment by diana7127** [comment]
终版mpv.net_CM菜单里没有rife_std的选项，我加的时候没看rife_std的设置，直接copy了当时mvtools_std在菜单里的名字，正在修正中

**Comment by Rakau** [comment]
> 因为“他写错了。” 我用std(standard)就只有标准的意思

ww，除了rife都有60，好像某些rife版本能自定义帧数来着

**Comment by hooke007** [comment]
你先看一下文档
https://github.com/hooke007/MPV_lazy/discussions/123

**Comment by Rakau** [comment]
> 你先看一下文档 [hooke007/MPV_lazy#123](https://github.com/hooke007/MPV_lazy/discussions/123)

了解
