### ISSUE TITLE
--secondary-sub-override 参数意义

### ISSUE THREAD

**Issue by QS0x01** [diana7127/mpv.net-DW#9]
非原版 mpv/mpv.net 参数，建议于 readme 添加相关说明，防止用户修改 mpv.conf 陷入困惑。

https://github.com/hooke007/MPV_lazy/discussions/61

**Comment by diana7127** [comment]
[更新说明](https://github.com/diana7127/mpv.net-DW/releases/tag/v1.5.0)里有写
